targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart # Specify the entry point
        options:
          compiler: dart2wasm
          # Optional: Add other dart2wasm options if needed
          # dart2wasm_args: ["--some-flag"]
