# Configures how builders are applied to this package ($default target).
# Builder definitions are in the packages that provide them (e.g., packages/atomic_styles/build.yaml).

targets:
  $default:
    builders:
      # Run the scanner on relevant dart files
      # Apply atomicScanner to the main package (dust_app)
      dust_atomic_styles|atomicScanner:
        enabled: true
        generate_for:
          - lib/**.dart
          - web/**.dart

      # Run the CSS writer, triggered by the .trigger file
      dust_atomic_styles|cssWriter: # Use the key defined in the builder's package build.yaml
        enabled: true
        generate_for:
          - web/atomic_styles.trigger # The trigger file
      # options: # Example if options were needed
      #   output: "web/atomic_styles.css" # This would override the default in the builder's options

      # Then run the web compiler
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart # Specify the entry point
        options:
          compiler: dart2wasm
          # Optional: Add other dart2wasm options if needed
          # dart2wasm_args: ["--some-flag"]
