name: dust_router
description: Router package for the Dust framework.
version: 0.0.1
publish_to: none # Prevent accidental publishing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dust_component:
    path: ../component # Assuming component package is adjacent

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
