name: dust_component
description: Core component model for the Dust web framework.
version: 0.0.1
# repository: https://github.com/your_org/dust/tree/main/packages/component # TODO: Update repository URL

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   meta: ^1.10.0 # Potentially needed for annotations later

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
