# Defines the builders provided by the dust_atomic_styles package.
builders:
  # Builder that scans .dart files and outputs .classes files (to cache)
  atomicScanner:
    import: "package:dust_atomic_styles/builder.dart"
    builder_factories: ["atomicStyleBuilder"]
    build_extensions: { ".dart": [".classes"] } # Output .classes files
    auto_apply: dependents # Apply to packages that depend on this one
    build_to: cache

  # Builder that writes the final aggregated CSS file
  cssWriter:
    import: "package:dust_atomic_styles/builder.dart"
    builder_factories: [
      "cssAggregatorBuilder",
    ] # Assuming factory name matches class
    # build_extensions are now defined within the Builder itself.
    # This builder reads inputs based on required_inputs and outputs to a fixed path.
    auto_apply: root_package # Should only be applied by the root package
    build_to: source
    # This builder needs to run after all atomicScanner instances have completed.
    required_inputs: [
      ".classes",
    ] # Depends on the output of atomicScanner. Ensures ordering.
# Optional: Configure output path via options
# defaults:
#   options:
#     output: "web/generated/atomic.css"

# Builder factories are defined in lib/builder.dart
