name: dust_atomic_styles
description: Atomic CSS generator for the Dust framework.
version: 0.0.1
publish_to: none # Not ready for publishing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.0 # Needed for Builder
  analyzer: ^6.0.0 # Needed for parsing Dart code

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
